name: gdbus_proxy_l1_tests

on:
  push:
    branches: [ main, develop, 'support/**', 'hotfix/**', 'topic/**']
  pull_request:
    branches: [ main, develop, 'support/**', 'hotfix/**', 'topic/**']

env:
  THUNDER_REF: "R4.4.3"

jobs:
  L1-tests:
    name: Build and run unit tests
    runs-on: ubuntu-22.04

    steps:
      # Set up Thunder cache
      - name: Set up Thunder cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            build/Thunder
            build/ThunderInterfaces
            build/ThunderTools
            install
            !install/etc/WPEFramework/plugins
            !install/usr/bin/gdbusproxy_l1_test
            !install/usr/include/gmock
            !install/usr/include/gtest
            !install/usr/lib/libgmockd.a
            !install/usr/lib/libgmock_maind.a
            !install/usr/lib/libgtestd.a
            !install/usr/lib/libgtest_maind.a
            !install/usr/lib/cmake/GTest
            !install/usr/lib/pkgconfig/gmock.pc
            !install/usr/lib/pkgconfig/gmock_main.pc
            !install/usr/lib/pkgconfig/gtest.pc
            !install/usr/lib/pkgconfig/gtest_main.pc
            !install/usr/lib/wpeframework/plugins
          key: thunder-${{ env.THUNDER_REF }}-gdbus
      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get install -y pkg-config libglib2.0-dev libnm-dev libcurl4-openssl-dev lcov ninja-build

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install jsonref

      - name: Configure CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: Checkout networkmanager
        uses: actions/checkout@v3
        with:
          path: networkmanager

      - name: Build networkmanager with Gnome GDBUS Proxy
        run: >
          cmake
          -S "${{github.workspace}}/networkmanager"
          -B build/networkmanager_gdbus
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DTHUNDER_VERSION="${{ env.THUNDER_REF }}"
          -DCMAKE_CXX_FLAGS=" -fprofile-arcs -ftest-coverage "
          -DENABLE_GNOME_NETWORKMANAGER=ON
          -DENABLE_GNOME_GDBUS=ON
          -DENABLE_PLUGIN_CLI=ON
          &&
          cmake --build build/networkmanager_gdbus --target install -j8


